FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends icecast2 wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY icecast.xml /etc/icecast2/icecast.xml
COPY entrypoint-icecast.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh && \
    chown icecast2:icecast /etc/icecast2/icecast.xml

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]
